INSERT INTO APP_USER (ID, USERNAME, PASSWORD_HASH, ROLE_NAME)
VALUES (1, 'admin', '$2a$10$6ORfQ0IEjQ8CQ6Wm1SDv4egEwMJ8lL6jb7n3YUX2f2v0KOuA9SuCG', 'ADMIN');

INSERT INTO USER_PROFILE (ID, EMAIL, FULL_NAME)
VALUES (1, 'admin@shop.com', 'System Admin');

INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (101, 'Gaming Mouse', 49.99);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (102, 'Mechanical Keyboard', 129.00);

INSERT INTO INVENTORY_ITEM (PRODUCT_ID, AVAILABLE_QTY, RESERVED_QTY) VALUES (101, 100, 0);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, AVAILABLE_QTY, RESERVED_QTY) VALUES (102, 70, 0);
