CREATE TABLE APP_USER (
  ID NUMBER(19) PRIMARY KEY,
  USERNAME VARCHAR2(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  ROLE_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE USER_PROFILE (
  ID NUMBER(19) PRIMARY KEY,
  EMAIL VARCHAR2(150) NOT NULL UNIQUE,
  FULL_NAME VARCHAR2(150) NOT NULL
);

CREATE TABLE PRODUCT (
  ID NUMBER(19) PRIMARY KEY,
  NAME VARCHAR2(150) NOT NULL,
  PRICE NUMBER(12,2) NOT NULL
);

CREATE TABLE INVENTORY_ITEM (
  PRODUCT_ID NUMBER(19) PRIMARY KEY,
  AVAILABLE_QTY NUMBER(10) NOT NULL,
  RESERVED_QTY NUMBER(10) NOT NULL
);

CREATE TABLE CUSTOMER_ORDER (
  ID NUMBER(19) PRIMARY KEY,
  USER_ID NUMBER(19) NOT NULL,
  PRODUCT_ID NUMBER(19) NOT NULL,
  QUANTITY NUMBER(10) NOT NULL,
  TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(30) NOT NULL
);

CREATE TABLE PAYMENT_TXN (
  ID NUMBER(19) PRIMARY KEY,
  ORDER_ID NUMBER(19) NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(30) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
