server: { port: 8086 }
spring:
  application: { name: payment-service }
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.payment.event"
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ECOM
    password: ECOMPass123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate: { ddl-auto: none }
    properties: { hibernate.dialect: org.hibernate.dialect.OracleDialect }
eureka:
  client: { service-url: { defaultZone: http://localhost:8761/eureka } }
app:
  jwt:
    secret: 7f57c9d4c17b456d9d2f829a1c0465cb7f57c9d4c17b456d9d2f829a1c0465cb
  kafka:
    topics:
      order-status: order-status-topic
