server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: ECOM
    password: ECOMPass123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.ecommerce.payment.event,com.ecommerce.order.event,com.ecommerce.inventory.event,com.ecommerce.*"
    properties:
      spring.json.trusted.packages: "com.ecommerce.payment.event,com.ecommerce.order.event,com.ecommerce.inventory.event,com.ecommerce.*"

app:
  kafka:
    topics:
      order-status: order-status-topic
  jwt:
    secret: 7f57c9d4c17b456c9d2f829a1c0465cb7f57c9d2f829a1c0465cb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
