server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ECOM
    password: ECOMPass123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: 7f57c9d4c17b456d9d2f829a1c0465cb7f57c9d4c17b456d9d2f829a1c0465cb
