server:
  port: 8087

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: ECOM
    password: ECOMPass123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
