INSERT INTO CART (ID, USERNAME, UPDATED_AT) VALUES (1, 'admin', SYSTIMESTAMP);
INSERT INTO CART_ITEM (ID, CART_ID, PRODUCT_ID, NAME, AMOUNT, QUANTITY) VALUES (1, 1, 101, 'Gaming Mouse', 49.99, 2);
INSERT INTO CART_ITEM (ID, CART_ID, PRODUCT_ID, NAME, AMOUNT, QUANTITY) VALUES (2, 1, 102, 'Mechanical Keyboard', 129.00, 1);
