-- Run this script as user ECOM on Oracle XE
-- Creates CART and CART_ITEM tables required by cart-service

-- Sequences for auto-increment IDs
CREATE SEQUENCE CART_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CART_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Cart table: one row per user
CREATE TABLE CART (
  ID         NUMBER(19)     NOT NULL,
  USERNAME   VARCHAR2(100)  NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_CART PRIMARY KEY (ID),
  CONSTRAINT UQ_CART_USERNAME UNIQUE (USERNAME)
);

-- Cart items: many items per cart
CREATE TABLE CART_ITEM (
  ID         NUMBER(19)    NOT NULL,
  CART_ID    NUMBER(19)    NOT NULL,
  PRODUCT_ID NUMBER(19)    NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  AMOUNT     NUMBER(10,2)  NOT NULL,
  QUANTITY   NUMBER(10)    NOT NULL,
  CONSTRAINT PK_CART_ITEM PRIMARY KEY (ID),
  CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CART(ID) ON DELETE CASCADE
);
