INSERT INTO APP_USER (ID, USERNAME, PASSWORD_HASH, ROLE_NAME)
VALUES (1, 'admin', '$2a$10$6ORfQ0IEjQ8CQ6Wm1SDv4egEwMJ8lL6jb7n3YUX2f2v0KOuA9SuCG', 'ADMIN');

INSERT INTO APP_USER (ID, USERNAME, PASSWORD_HASH, ROLE_NAME)
VALUES (2, 'user', '$2a$10$6ORfQ0IEjQ8CQ6Wm1SDv4egEwMJ8lL6jb7n3YUX2f2v0KOuA9SuCG', 'USER');

INSERT INTO USER_PROFILE (ID, EMAIL, FULL_NAME)
VALUES (1, 'admin@shop.com', 'System Admin');

INSERT INTO USER_PROFILE (ID, EMAIL, FULL_NAME)
VALUES (2, 'user@shop.com', 'Normal User');

INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (101, 'Gaming Mouse', 49.99);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (102, 'Mechanical Keyboard', 129.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (103, 'Wireless Headset', 89.00);

INSERT INTO INVENTORY_ITEM (PRODUCT_ID, AVAILABLE_QTY, RESERVED_QTY) VALUES (101, 100, 0);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, AVAILABLE_QTY, RESERVED_QTY) VALUES (102, 70, 0);
INSERT INTO INVENTORY_ITEM (PRODUCT_ID, AVAILABLE_QTY, RESERVED_QTY) VALUES (103, 50, 0);

INSERT INTO ORDERS (ID, CUSTOMER_ID, TOTAL_AMOUNT, STATUS, PAYMENT_STATUS) VALUES (1001, 2, 49.99, 'PENDING', 'PENDING');
INSERT INTO ORDER_ITEM (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (2001, 1001, 101, 1, 49.99);

INSERT INTO PAYMENT_TRANSACTION (ID, ORDER_ID, AMOUNT, METHOD, STATUS, TRANSACTION_REF) VALUES (3001, 1001, 49.99, 'VNPAY', 'PENDING', 'VNP_1001_001');
