CREATE TABLE APP_USER (
  ID NUMBER PRIMARY KEY,
  USERNAME VARCHAR2(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  ROLE_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE USER_PROFILE (
  ID NUMBER PRIMARY KEY,
  EMAIL VARCHAR2(150),
  FULL_NAME VARCHAR2(150)
);

CREATE TABLE PRODUCT (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(200) NOT NULL,
  PRICE NUMBER(10,2) NOT NULL
);

CREATE TABLE INVENTORY_ITEM (
  PRODUCT_ID NUMBER PRIMARY KEY,
  AVAILABLE_QTY NUMBER DEFAULT 0,
  RESERVED_QTY NUMBER DEFAULT 0
);

CREATE TABLE ORDERS (
  ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER NOT NULL,
  TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
  STATUS VARCHAR2(50) NOT NULL,
  PAYMENT_STATUS VARCHAR2(50) NOT NULL
);

CREATE TABLE ORDER_ITEM (
  ID NUMBER PRIMARY KEY,
  ORDER_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  QUANTITY NUMBER NOT NULL,
  UNIT_PRICE NUMBER(10,2) NOT NULL
);

CREATE TABLE PAYMENT_TRANSACTION (
  ID NUMBER PRIMARY KEY,
  ORDER_ID NUMBER NOT NULL,
  AMOUNT NUMBER(10,2) NOT NULL,
  METHOD VARCHAR2(50) NOT NULL,
  STATUS VARCHAR2(50) NOT NULL,
  TRANSACTION_REF VARCHAR2(100)
);

-- Cart tables
CREATE SEQUENCE CART_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CART_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CART (
  ID         NUMBER(19)    NOT NULL,
  USERNAME   VARCHAR2(100) NOT NULL,
  UPDATED_AT TIMESTAMP,
  CONSTRAINT PK_CART PRIMARY KEY (ID),
  CONSTRAINT UQ_CART_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE CART_ITEM (
  ID         NUMBER(19)    NOT NULL,
  CART_ID    NUMBER(19)    NOT NULL,
  PRODUCT_ID NUMBER(19)    NOT NULL,
  NAME       VARCHAR2(200) NOT NULL,
  AMOUNT     NUMBER(10,2)  NOT NULL,
  QUANTITY   NUMBER(10)    NOT NULL,
  CONSTRAINT PK_CART_ITEM PRIMARY KEY (ID),
  CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CART(ID) ON DELETE CASCADE
);
